repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: uv-run-ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: uv-run-ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: uv-run-pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        require_serial: true
